# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hello_text', models.CharField(max_length=200)),
                ('times', models.IntegerField(default=0)),
            ],
        ),
    ]
