# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0002_auto_20171102_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_title', models.CharField(max_length=200)),
                ('topic_detail', models.CharField(max_length=200)),
                ('topic_time', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Count',
        ),
    ]
